name: DockerHub

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  multiarch-build-alpine:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Get Docker tags for Alpine based image
        id: docker_meta_alpine
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            neilpang/docker-hoster
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: login to docker hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push the Alpine based image
        id: docker_build_alpine
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/s390x
          push: true
          tags: ${{ steps.docker_meta_alpine.outputs.tags }}
          labels: ${{ steps.docker_meta_alpine.outputs.labels }}

      - name: Images digests
        run: echo ${{ steps.docker_build_alpine.outputs.digest }}
